spring.application.name=saberpro

# MySQL Clever Cloud
spring.datasource.url=jdbc:mysql://uwnnqwnl2g9x2jjz:TUc1G6m5MHZGMBaScTIU@bznc8nf3ssfewbrrmw9w-mysql.services.clever-cloud.com:3306/bznc8nf3ssfewbrrmw9w
spring.datasource.username=uwnnqwnl2g9x2jjz
spring.datasource.password=TUc1G6m5MHZGMBaScTIU
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Limitar conexiones Clever Cloud DEV
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Puerto
server.port=${PORT:8086}
# Archivos recibo de pago Saber Pro
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
